[tool.poetry]
name = "pyusbsim800c"
version = "0"
description = ""
authors = ["tloki"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
